# .github/workflows/deploy.yml
name: CI/CD Portfolio

on:
  push:
    branches:
      - main # O la rama principal de tu proyecto, ej. master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta a la versión de Node.js que uses en tu proyecto
          cache: 'npm' # Habilita el caché de npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps # Opcional: usa --legacy-peer-deps si tienes problemas de dependencias con npm install

      - name: Run unit tests
        # Este comando ejecutará Vitest. Asegúrate de que tu package.json tenga
        # en scripts: "test": "vitest"
        run: npm test

      - name: Build project with Vite
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # La carpeta de salida de Vite es 'dist'
